import {
  DINCO_ENGINEERING_CONSTRUCTIONCONST,
  INVENTORY_MANAGEMENT,
  OKR_MANAGEMENT,
  PROJECT_MANAGEMENT,
  DUFAGO_COMMERCIAL_CONCETE,
  OKR_PERFORMANCE_MANAGEMENT,
  DUFAGO_INVENTORY_MANAGEMENT,
  DUFAGO_PRODUCTION_MANAGEMENT,
  DUFAGO_ACCOUNTANT_MANAGEMENT,
  CONCRETE_TRANSPORT_TRUCK_MANAGEMENT,
  HUYTAN_CUSTOMER_RELATIONSHIP_MANAGEMENT,
  NGOC_THY_HONDA_MOTORCYCLE_DEALER,
  THIEU_YEN_HONDA_MOTORCYCLE_DEALER,
  VINFAST_AUTO_THANH_HOA,
  RUOU_NGON,
  POWER_BI,
  QUOCTIEN_CUSTOMER_RELATIONSHIP_MANAGEMENT,
  QUOCTIEN_APP_DROS,
} from 'src/assets/data/caseStudies';
import { CONCRETE_TRANSPORT_TRUCK_MANAGEMENT_JP, DINCO_ENGINEERING_CONSTRUCTIONCONST_JP, DUFAGO_ACCOUNTANT_MANAGEMENT_JP, DUFAGO_COMMERCIAL_CONCRETE_JP, DUFAGO_INVENTORY_MANAGEMENT_JP, DUFAGO_PRODUCTION_MANAGEMENT_JP, HUYTAN_CUSTOMER_RELATIONSHIP_MANAGEMENT_JP, INVENTORY_MANAGEMENT_JP, NGOC_THY_HONDA_MOTORCYCLE_DEALER_JP, OKR_MANAGEMENT_JP, OKR_PERFORMANCE_MANAGEMENT_JP, POWER_BI_JP, PROJECT_MANAGEMENT_JP, QUOCTIEN_APP_DROS_JP, QUOCTIEN_CUSTOMER_RELATIONSHIP_MANAGEMENT_JP, RUOU_NGON_JP, THIEU_YEN_HONDA_MOTORCYCLE_DEALER_JP, VINFAST_AUTO_THANH_HOA_JP } from 'src/assets/data/jp-case';

// ----------------------------------------------------------------------

export const DATAS = [
  {
    id: 'dinco-engineering-construction',
    title: 'DINCO ENGINEERING & CONSTRUCTION',
    breadcrumbs: 'Human Resource Management',
    category: 'Human Resource Management',
    website: 'www.dinco.com.vn',
    description:
      'DINCO E&C is a leading construction company specializing in industrial warehouses, high-rise buildings, hotels, resorts, and infrastructure projects.',
    content: DINCO_ENGINEERING_CONSTRUCTIONCONST,
    createdAt: '08 September 2022',
    heroUrl: '/assets/images/caseStudies/dinco-engineering-construction-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/dinco-engineering-construction-img-1.png',
      '/assets/images/caseStudies/dinco-engineering-construction-img-2.png',
      '/assets/images/caseStudies/dinco-engineering-construction-img-3.png',
    ],
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Sa Tran',
      role: 'Compensation and Benefits',
      avatarUrl: '/assets/images/avatar/customer/sa-tran.png',
      review: `"The HRM software with features like Automated Payroll Processing, Performance Review Module, and Employee Mobility Management is truly useful, time-saving and improves the efficiency of the HR department's operations."`,
    },
  },
  {
    id: 'project-management',
    title: 'DINCO ENGINEERING & CONSTRUCTION',
    breadcrumbs: 'Project Management',
    category: 'Project Management',
    website: 'www.dinco.com.vn',
    description:
      'DINCO E&C is a leading construction company specializing in industrial warehouses, high-rise buildings, hotels, resorts, and infrastructure projects.',
    content: PROJECT_MANAGEMENT,
    createdAt: '22 December 2022',
    heroUrl: '/assets/images/caseStudies/project-management-hero.png',
    imageCover: '/assets/images/caseStudies/project-management-cover.jpg',
    galleryImgs: [
      '/assets/images/caseStudies/project-management-img-1.png',
      '/assets/images/caseStudies/project-management-img-2.png',
    ],
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Vung Vo',
      role: 'Project Quality Assuror',
      avatarUrl: '/assets/images/avatar/customer/Vung-Vo.png',
      review: `
      "The project management software with features like Centralized Issue Tracking, Automated Notifications, and Real-Time Reporting helps me easily monitor and ensure project quality."      `,
    },
  },
  {
    id: 'inventory-management',
    title: 'DINCO ENGINEERING & CONSTRUCTION',
    breadcrumbs: 'Inventory Management',
    category: 'Inventory Management',
    website: 'www.dinco.com.vn',
    description:
      'DINCO E&C is a leading construction company specializing in industrial warehouses, high-rise buildings, hotels, resorts, and infrastructure projects.',
    content: INVENTORY_MANAGEMENT,
    createdAt: '03 March 2023',
    heroUrl: '/assets/images/caseStudies/inventory-management-hero.png',
    galleryImgs: false,
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Lam Ta',
      role: 'Warehouse Manager',
      avatarUrl: '/assets/images/avatar/customer/lam-ta.png',
      review: `
      "The warehouse management software with features like Enhanced Supervision, Quantity Control and Forecasting, and Comprehensive Inventory Management helps me manage the warehouse efficiently and optimize operations."`,
    },
  },
  {
    id: 'okr-management',
    title: 'DINCO ENGINEERING & CONSTRUCTION',
    breadcrumbs: 'OKR & Performance Management',
    category: 'OKR & Performance Management',
    website: 'www.dinco.com.vn',
    description:
      'DINCO E&C is a leading construction company specializing in industrial warehouses, high-rise buildings, hotels, resorts, and infrastructure projects.',
    content: OKR_MANAGEMENT,
    createdAt: '12 June 2022',
    heroUrl: '/assets/images/caseStudies/okr-management-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/okr-management-img-1.png',
      '/assets/images/caseStudies/okr-management-img-2.png',
      '/assets/images/caseStudies/okr-management-img-3.png',
    ],
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Phuong Nguyen',
      role: 'Structural Team Leader',
      avatarUrl: '/assets/images/avatar/customer/phuong-nguyen.png',
      review: `
      "The OKRs software with customizable OKR framework, performance analytics and reporting, and real-time monitoring and progress tracking helps me easily set goals, monitor and improve my team's work efficiency."`,
    },
  },
  {
    id: 'dufago-commercial-concete',
    title: 'DUFAGO CONSTRUCTION MATERIALS CORPORATION',
    breadcrumbs: 'Human Resource Management',
    category: 'Human Resource Management',
    website: 'www.dinco.com.vn',
    description:
      'Dufago is a commercial concrete manufacturing company operating in Central Vietnam with five large production stations, each capable of producing 10,000 cubic meters of concrete per month.',
    content: DUFAGO_COMMERCIAL_CONCETE,
    createdAt: '23 March 2023',
    heroUrl: '/assets/images/caseStudies/dufago-commercial-concete-hero.png',
    imageCover: '/assets/images/caseStudies/dufago-commercial-concete-cover.png',
    galleryImgs: false,
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Dung Phan',
      role: 'Head of Human Resources',
      avatarUrl: '/assets/images/avatar/customer/dung-phan.png',
      review: `
      "The HRM software with features like work history tracking, recruitment management, and dedicated functionalities for the head of HR helps me manage human resources efficiently, save time, and improve department operations."`,
    },
  },
  {
    id: 'okr-performance-management',
    title: 'DUFAGO CONSTRUCTION MATERIALS CORPORATION',
    breadcrumbs: 'OKR & Performance Management',
    category: 'OKR & Performance Management',
    website: 'www.dufago.com.vn',
    description:
      'Dufago is a commercial concrete manufacturing company operating in Central Vietnam with five large production stations, each capable of producing 10,000 cubic meters of concrete per month.',
    content: OKR_PERFORMANCE_MANAGEMENT,
    createdAt: '12 December 2022',
    heroUrl: '/assets/images/caseStudies/okr-performance-management-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/okr-performance-management-img-1.png',
      '/assets/images/caseStudies/okr-performance-management-img-2.png',
    ],
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Trieu Nguyen',
      role: 'Sales Director',
      avatarUrl: '/assets/images/avatar/customer/trieu-nguyen.png',
      review: `
      "The OKRs software with features like Streamlined Goal Management, Objective Alignment, and Data-Driven Decision-Making helps the management board strategically align and improve business performance."`,
    },
  },
  {
    id: 'dufago-inventory-management',
    title: 'DUFAGO CONSTRUCTION MATERIALS CORPORATION',
    breadcrumbs: 'Inventory Management',
    category: 'Inventory Management',
    website: 'www.dufago.com.vn',
    description:
      'Dufago is a commercial concrete manufacturing company operating in Central Vietnam with five large production stations, each capable of producing 10,000 cubic meters of concrete per month.',
    content: DUFAGO_INVENTORY_MANAGEMENT,
    createdAt: '04 March 2022',
    heroUrl: '/assets/images/caseStudies/dufago-inventory-management-hero.png',
    galleryImgs: false,
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Binh Nguyen',
      role: 'Warehouse Manager',
      avatarUrl: '/assets/images/avatar/customer/binh-nguyen.jpg',
      review: `
      "The warehouse management software with features like Standardized Inventory Management, Real-time Inventory Updates, and Data-Driven Decision-Making helps me enhance warehouse and supply chain operations efficiency."`,
    },
  },
  {
    id: 'dufago-production-management',
    title: 'DUFAGO CONSTRUCTION MATERIALS CORPORATION',
    breadcrumbs: 'Production Management',
    category: 'Production Management',
    website: 'www.dufago.com.vn',
    description:
      'Dufago is a commercial concrete manufacturing company operating in Central Vietnam with five large production stations, each capable of producing 10,000 cubic meters of concrete per month.',
    content: DUFAGO_PRODUCTION_MANAGEMENT,
    createdAt: '10 April 2023',
    heroUrl: '/assets/images/caseStudies/dufago-production-management-hero.png',
    galleryImgs: false,
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Sinh Nguyen',
      role: 'Production Manager',
      avatarUrl: '/assets/images/avatar/customer/sinh-nguyen.png',
      review: `
      "This concrete production management software is truly invaluable. The advanced production scheduling, efficient delivery coordination, and material/product tracking features are helping us significantly optimize our production processes."`,
    },
  },
  {
    id: 'dufago-accountant-management',
    title: 'DUFAGO CONSTRUCTION MATERIALS CORPORATION',
    breadcrumbs: 'Accounting & Finance Management',
    category: 'Accounting & Finance Management',
    website: 'www.dufago.com.vn',
    description:
      'Dufago is a commercial concrete manufacturing company operating in Central Vietnam with five large production stations, each capable of producing 10,000 cubic meters of concrete per month.',
    content: DUFAGO_ACCOUNTANT_MANAGEMENT,
    createdAt: '14 September 2023',
    heroUrl: '/assets/images/caseStudies/dufago-accountant-management-hero.png',
    galleryImgs: false,
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Thiep Duong',
      role: 'Financial Manager',
      avatarUrl: '/assets/images/avatar/customer/thiep-duong.png',
      review: `
      "This financial management software is a game-changer. The streamlined financial data management, enhanced customer debt management, and detailed business activity performance reports are making our financial operations more efficient and insightful than ever before."`,
    },
  },
  {
    id: 'concrete-transport-truck-management',
    title: 'DUFAGO CONSTRUCTION MATERIALS CORPORATION',
    breadcrumbs: 'Concrete Transport Truck Management',
    category: 'Concrete Transport Truck Management',
    website: 'www.dufago.com.vn',
    description:
      'Dufago is a commercial concrete manufacturing company operating in Central Vietnam with five large production stations, each capable of producing 10,000 cubic meters of concrete per month.',
    content: CONCRETE_TRANSPORT_TRUCK_MANAGEMENT,
    createdAt: '27 June 2023',
    heroUrl: '/assets/images/caseStudies/concrete-transport-truck-management-hero.png',
    galleryImgs: false,
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Trong Tran',
      role: 'Device Manager',
      avatarUrl: '/assets/images/avatar/customer/trong-tran.jpg',
      review: `
      "This equipment management software is really making a difference for our fleet management. It helps us keep an eye on revenue, manage maintenance costs, monitor routes, and track fuel consumption, which ultimately boosts our efficiency and savings."`,
    },
  },
  {
    id: 'huytan-customer-relationship-management',
    title: 'HUY TAN Honda Motorcycle Dealer',
    breadcrumbs: 'Customer Relationship Management',
    category: 'Customer Relationship Management',
    website: null,
    description:
      'Huy Tân is a motorcycle dealership system in Nha Trang, Vietnam. It comprises four authorized Honda dealerships in the area.',
    content: HUYTAN_CUSTOMER_RELATIONSHIP_MANAGEMENT,
    createdAt: '05 May 2023',
    heroUrl: '/assets/images/caseStudies/huytan-customer-relationship-management-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/huytan-customer-relationship-management-img-1.png',
      '/assets/images/caseStudies/huytan-customer-relationship-management-img-2.png',
      '/assets/images/caseStudies/huytan-customer-relationship-management-img-3.png',
      '/assets/images/caseStudies/huytan-customer-relationship-management-img-4.png',
    ],
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MSSQL',
    },
    testimonial: {
      name: 'Nga Pham',
      role: 'Sales Manager',
      avatarUrl: '/assets/images/avatar/customer/nga-pham.jpg',
      review: `
      "This sales management software has been a real asset to our sales team. With its merchandise inspection tool, real-time pricing lookup, automated sales invoices, and advanced reporting features, it has greatly streamlined our sales operations and enhanced our customer service."`,
    },
  },
  {
    id: 'ngoc-thi-honda-motorcycle-dealer',
    title: 'NGOC THY Honda Motorcycle Dealer',
    breadcrumbs: 'Customer Relationship Management',
    category: 'Customer Relationship Management',
    website: '',
    description:
      'Ngoc Thy is a motorcycle and automobile dealership network located in Kontum, Vietnam. They offer various automotive brands and operate more than 10 stores in their network.',
    content: NGOC_THY_HONDA_MOTORCYCLE_DEALER,
    createdAt: '28 October 2022',
    heroUrl: '/assets/images/caseStudies/ngoc-thi-honda-motorcycle-dealer-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/ngoc-thi-honda-motorcycle-dealer-img-1.png',
      '/assets/images/caseStudies/ngoc-thi-honda-motorcycle-dealer-img-2.png',
      '/assets/images/caseStudies/ngoc-thi-honda-motorcycle-dealer-img-3.png',
    ],
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MSSQL',
    },
    testimonial: {
      name: 'Hien Hoang',
      role: 'Repair Service Manager',
      avatarUrl: '/assets/images/avatar/customer/hien-hoang.png',
      review: `
      "This iPad app helps us perform repairs more quickly and easily, making our repair service more robust and efficient."`,
    },
  },
  {
    id: 'thieu-yen-honda-motorcycle-dealer',
    title: 'THIEU YEN Honda Motorcycle Dealer',
    breadcrumbs: 'Inventory Management',
    category: 'Inventory Management',
    website: false,
    description:
      'Huy Tan is a motorcycle dealership network in Nha Trang, Vietnam, with four authorized Honda dealerships and more than 100 employees.',
    content: THIEU_YEN_HONDA_MOTORCYCLE_DEALER,
    createdAt: '05 September 2022',
    heroUrl: '/assets/images/caseStudies/thieu-yen-honda-motorcycle-dealer-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/thieu-yen-honda-motorcycle-dealer-img-1.png',
      '/assets/images/caseStudies/thieu-yen-honda-motorcycle-dealer-img-2.png',
    ],
    technologies: {
      frontend: 'WinForms',
      backend: 'C#',
      database: 'MSSQL',
    },
    testimonial: {
      name: 'Khanh Phan',
      role: 'Spare Parts Manager',
      avatarUrl: '/assets/images/avatar/customer/khanh-phan.jpeg',
      review: `
      "The software for managing motorcycle spare parts with Network-Wide Visibility, Value Tracking, and Analytics features enhances inventory optimization. It efficiently aids in network management, profit optimization, and business performance improvement."`,
    },
  },
  {
    id: 'vinfast-auto-thanh-hoa',
    title: 'VINFAST AUTO THANH HOA',
    breadcrumbs: 'Customer Relationship Management',
    category: 'Customer Relationship Management',
    website: 'www.vinfast-thanhhoa.com',
    description: null,
    content: VINFAST_AUTO_THANH_HOA,
    createdAt: '30 October 2023',
    heroUrl: '/assets/images/caseStudies/vinfast-auto-thanh-hoa-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/vinfast-auto-thanh-hoa-img-1.png',
      '/assets/images/caseStudies/vinfast-auto-thanh-hoa-img-2.png',
    ],
    technologies: {
      frontend: 'Bootstrap, ReactJS',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Dung Le',
      role: 'Executive Director',
      avatarUrl: '/assets/images/avatar/customer/dung-le.jpg',
      review: `
      "CRM software with features like Improved Appointment Conversion Rate, Sales Productivity Boost, Incentive Accuracy, and Staff Satisfaction has significantly enhanced our business performance."`,
    },
  },
  {
    id: 'ruou-ngon',
    title: 'RUOU NGON',
    breadcrumbs: 'Customer Relationship Management',
    category: 'Customer Relationship Management',
    website: 'www.ruoungon.vn',
    description:
      'Rượu Ngon Company is a nationwide retail chain in Vietnam, specializing in providing genuine imported wines of high quality.',
    content: RUOU_NGON,
    createdAt: '19 September 2023',
    heroUrl: '/assets/images/caseStudies/ruou-ngon-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/ruou-ngon-img-1.png',
      '/assets/images/caseStudies/ruou-ngon-img-2.png',
    ],
    technologies: {
      frontend: 'Bootstrap, ReactJS',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Ngoc Mai',
      role: 'Manager',
      avatarUrl: '/assets/images/avatar/customer/ngoc-mai.jpg',
      review: `
      "CRM software with Sales Target Automation, Error-Proof Pricing, and Inventory Management features has streamlined our operations and improved efficiency."`,
    },
  },
  {
    id: 'power-bi',
    title: 'QUOC TIEN HONDA MOTORCYCLE DEALER',
    breadcrumbs: 'Power BI',
    category: 'Business Intelligence',
    website: 'www.quoctien.vn',
    description:
      'The Quoc Tien Motorcycle System operates more than 8 stores and employs over 200 staff in the Da Nang and Quang Nam areas, specializing in the sales and genuine Honda motorcycle repairs.',
    content: POWER_BI,
    createdAt: '25 October 2019',
    heroUrl: '/assets/images/caseStudies/power-bi-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/power-bi-img-1.png',
      '/assets/images/caseStudies/power-bi-img-2.png',
    ],
    technologies: {
      frontend: 'Power BI Desktop, Power BI Mobile',
      backend: 'Power BI Service',
      database: 'MSSQL',
    },
    testimonial: {
      name: 'Hien Dinh',
      role: 'Head of Business Operations',
      avatarUrl: '/assets/images/avatar/customer/hien-dinh.jpg',
      review: `
      "Thanks to its Agile Reporting System and Mobile Accessibility, we can effortlessly examine data from anywhere and at any time, significantly improving our decision-making process!"`,
    },
  },
  {
    id: 'quoc-tien-honda-motorcycle-dealer',
    title: 'QUOC TIEN HONDA MOTORCYCLE DEALER',
    breadcrumbs: 'Auto HMS',
    category: 'Robotic Process Automation',
    website: 'www.quoctien.vn',
    description:
      'The Quoc Tien Motorcycle System operates more than 8 stores and employs over 200 staff in the Da Nang and Quang Nam areas, specializing in the sales and genuine Honda motorcycle repairs.',
    content: QUOCTIEN_CUSTOMER_RELATIONSHIP_MANAGEMENT,
    createdAt: '30 March 2018',
    heroUrl: '/assets/images/caseStudies/quoc-tien-honda-motorcycle-dealer-hero.png',
    galleryImgs: [
      '/assets/images/caseStudies/quoc-tien-honda-motorcycle-dealer-img-1.png',
      '/assets/images/caseStudies/quoc-tien-honda-motorcycle-dealer-img-2.png',
    ],
    technologies: {
      frontend: 'UiPath Studio',
      backend: 'UiPath Service',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Vu Nguyen',
      role: 'HMS Team Leader',
      avatarUrl: '/assets/images/avatar/customer/vu-nguyen.jpg',
      review: `
      "The Auto Bots HMS has made a significant impact on our operations. It has greatly reduced manual data entry and improved our efficiency. This has saved us money and allowed us to manage our service quality more effectively through score criteria management."`,
    },
  },
  {
    id: 'quoc-tien-app-dros',
    title: 'QUOC TIEN HONDA MOTORCYCLE DEALER',
    breadcrumbs: 'Auto DROS',
    category: 'Robotic Process Automation',
    website: 'www.quoctien.vn',
    description:
      'The Quoc Tien Motorcycle System operates more than 8 stores and employs over 200 staff in the Da Nang and Quang Nam areas, specializing in the sales and genuine Honda motorcycle repairs.',
    content: QUOCTIEN_APP_DROS,
    createdAt: '19 September 2023',
    heroUrl: '/assets/images/caseStudies/quoc-tien-app-dros-hero.png',
    galleryImgs: false,
    technologies: {
      frontend: 'Bootstrap, Jquery',
      backend: 'PHP Laravel',
      database: 'MySQL',
    },
    testimonial: {
      name: 'Hieu Nguyen',
      role: 'IT Team Leader',
      avatarUrl: '/assets/images/avatar/customer/hieu-nguyen.jpg',
      review: `
      "Utilizing Dros Auto Bots helps minimize time-consuming data entry, streamline complex data processing, and provide real-time reporting, ultimately enhancing our team's efficiency and timely tracking capabilities."`,
    },
  },
];

export const _curentCaseStudies = DATAS.map((_, index) => ({
  id: DATAS[index]?.id,
  content: DATAS[index]?.content,
  title: DATAS[index]?.title,
  breadcrumbs: DATAS[index]?.breadcrumbs,
  category: DATAS[index]?.category,
  createdAt: DATAS[index]?.createdAt,
  website: DATAS[index]?.website,
  description: DATAS[index]?.description,
  heroUrl: DATAS[index]?.heroUrl,
  imageCover: DATAS[index]?.imageCover,
  galleryImgs: DATAS[index].galleryImgs,
  coverUrl: `/assets/images/marketing/marketing_${index + 1}.jpg`,
  imageSrc: `/assets/images/marketing/marketing_${index + 1}.jpg`,
  technologies: {
    frontend: DATAS[index]?.technologies?.frontend,
    backend: DATAS[index]?.technologies?.backend,
    database: DATAS[index]?.technologies?.database,
  },
  testimonial: {
    name: DATAS[index]?.testimonial?.name,
    role: DATAS[index]?.testimonial?.role,
    avatarUrl: DATAS[index]?.testimonial?.avatarUrl,
    review: DATAS[index]?.testimonial?.review,
  },
}));

export const getDatas = (t, locale = 'en') => [
    {
      id: 'dinco-engineering-construction',
      title: t('dinco-engineering-construction.title'),
      breadcrumbs: t('dinco-engineering-construction.breadcrumbs'),
      category: t('dinco-engineering-construction.category'),
      website: 'www.dinco.com.vn',
      description: t('dinco-engineering-construction.description'),
      content: locale === 'jp' ? DINCO_ENGINEERING_CONSTRUCTIONCONST_JP : DINCO_ENGINEERING_CONSTRUCTIONCONST,
      createdAt: '08 September 2022',
      heroUrl: '/assets/images/caseStudies/dinco-engineering-construction-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/dinco-engineering-construction-img-1.png',
        '/assets/images/caseStudies/dinco-engineering-construction-img-2.png',
        '/assets/images/caseStudies/dinco-engineering-construction-img-3.png',
      ],
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Sa Tran',
        role:  t('dinco-engineering-construction.role'),
        avatarUrl: '/assets/images/avatar/customer/sa-tran.png',
        review: t('dinco-engineering-construction.review'),
      },
    },
    {
      id: 'project-management',
      title: t('project-management.title'),
      breadcrumbs: t('project-management.breadcrumbs'),
      category: t('project-management.category'),
      website: 'www.dinco.com.vn',
      description: t('project-management.description'),
      content: locale === 'jp' ? PROJECT_MANAGEMENT_JP : PROJECT_MANAGEMENT,
      createdAt: '22 December 2022',
      heroUrl: '/assets/images/caseStudies/project-management-hero.png',
      imageCover: '/assets/images/caseStudies/project-management-cover.jpg',
      galleryImgs: [
        '/assets/images/caseStudies/project-management-img-1.png',
        '/assets/images/caseStudies/project-management-img-2.png',
      ],
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Vung Vo',
        role: t('project-management.role'),
        avatarUrl: '/assets/images/avatar/customer/Vung-Vo.png',
        review: t('project-management.review'), 
      },
    },
    {
      id: 'inventory-management',
      title: t('inventory-management.title'),
      breadcrumbs: t('inventory-management.breadcrumbs'),
      category: t('inventory-management.category'),
      website: 'www.dinco.com.vn',
      description: t('inventory-management.description'),
      content: locale === 'jp' ? INVENTORY_MANAGEMENT_JP : INVENTORY_MANAGEMENT,
      createdAt: '03 March 2023',
      heroUrl: '/assets/images/caseStudies/inventory-management-hero.png',
      galleryImgs: false,
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Lam Ta',
        role: t('inventory-management.role'),
        avatarUrl: '/assets/images/avatar/customer/lam-ta.png',
        review: t('inventory-management.review'),
      },
    },
    {
      id: 'okr-management',
      title: t('okr-management.title'),
      breadcrumbs: t('okr-management.breadcrumbs'),
      category: t('okr-management.category'),
      website: 'www.dinco.com.vn',
      description: t('okr-management.description'),
      content: locale === 'jp' ? OKR_MANAGEMENT_JP : OKR_MANAGEMENT,
      createdAt: '12 June 2022',
      heroUrl: '/assets/images/caseStudies/okr-management-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/okr-management-img-1.png',
        '/assets/images/caseStudies/okr-management-img-2.png',
        '/assets/images/caseStudies/okr-management-img-3.png',
      ],
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Phuong Nguyen',
        role: t('okr-management.role'),
        avatarUrl: '/assets/images/avatar/customer/phuong-nguyen.png',
        review: t('okr-management.review'),
      },
    },
    {
      id: 'dufago-commercial-concete',
      title: t('dufago-commercial-concete.title'),
      breadcrumbs: t('dufago-commercial-concete.breadcrumbs'),
      category: t('dufago-commercial-concete.category'),
      website: 'www.dinco.com.vn',
      description: t('dufago-commercial-concete.description'),
      content: locale === 'jp' ? DUFAGO_COMMERCIAL_CONCRETE_JP : DUFAGO_COMMERCIAL_CONCETE,
      createdAt: '23 March 2023',
      heroUrl: '/assets/images/caseStudies/dufago-commercial-concete-hero.png',
      imageCover: '/assets/images/caseStudies/dufago-commercial-concete-cover.png',
      galleryImgs: false,
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Dung Phan',
        role: t('dufago-commercial-concete.role'),
        avatarUrl: '/assets/images/avatar/customer/dung-phan.png',
        review: t('dufago-commercial-concete.review'),
      },
    },
    {
      id: 'okr-performance-management',
      title: t('okr-performance-management.title'),
      breadcrumbs: t('okr-performance-management.breadcrumbs'),
      category: t('okr-performance-management.category'),
      website: 'www.dufago.com.vn',
      description: t('okr-performance-management.description'),
      content: locale === 'jp' ? OKR_PERFORMANCE_MANAGEMENT_JP : OKR_PERFORMANCE_MANAGEMENT,
      createdAt: '12 December 2022',
      heroUrl: '/assets/images/caseStudies/okr-performance-management-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/okr-performance-management-img-1.png',
        '/assets/images/caseStudies/okr-performance-management-img-2.png',
      ],
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Trieu Nguyen',
        role:  t('okr-performance-management.role'),
        avatarUrl: '/assets/images/avatar/customer/trieu-nguyen.png',
        review: t('okr-performance-management.review'),
      },
    },
    {
      id: 'dufago-inventory-management',
      title: t('dufago-inventory-management.title'),
      breadcrumbs: t('dufago-inventory-management.breadcrumbs'),
      category: t('dufago-inventory-management.category'),
      website: 'www.dufago.com.vn',
      description: t('dufago-inventory-management.description'),
      content: locale === 'jp' ? DUFAGO_INVENTORY_MANAGEMENT_JP : DUFAGO_INVENTORY_MANAGEMENT,
      createdAt: '04 March 2022',
      heroUrl: '/assets/images/caseStudies/dufago-inventory-management-hero.png',
      galleryImgs: false,
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Binh Nguyen',
        role: t('dufago-inventory-management.role'),
        avatarUrl: '/assets/images/avatar/customer/binh-nguyen.jpg',
        review: t('dufago-inventory-management.review'),
      },
    },
    {
      id: 'dufago-production-management',
      title: t('dufago-production-management.title'),
      breadcrumbs: t('dufago-production-management.breadcrumbs'),
      category: t('dufago-production-management.category'),
      website: 'www.dufago.com.vn',
      description:  t('dufago-production-management.description'),
      content: locale === 'jp' ? DUFAGO_PRODUCTION_MANAGEMENT_JP : DUFAGO_PRODUCTION_MANAGEMENT,
      createdAt: '10 April 2023',
      heroUrl: '/assets/images/caseStudies/dufago-production-management-hero.png',
      galleryImgs: false,
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Sinh Nguyen',
        role: t('dufago-production-management.role'),
        avatarUrl: '/assets/images/avatar/customer/sinh-nguyen.png',
        review: t('dufago-production-management.review'),
      },
    },
    {
      id: 'dufago-accountant-management',
      title: t('dufago-accountant-management.title'),
      breadcrumbs: t('dufago-accountant-management.breadcrumbs'),
      category: t('dufago-accountant-management.category'),
      website: 'www.dufago.com.vn',
      description: t('dufago-accountant-management.description'),
      content: locale === 'jp' ? DUFAGO_ACCOUNTANT_MANAGEMENT_JP : DUFAGO_ACCOUNTANT_MANAGEMENT,
      createdAt: '14 September 2023',
      heroUrl: '/assets/images/caseStudies/dufago-accountant-management-hero.png',
      galleryImgs: false,
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Thiep Duong',
        role: t('dufago-accountant-management.role'),
        avatarUrl: '/assets/images/avatar/customer/thiep-duong.png',
        review: t('dufago-accountant-management.review'),
      },
    },
    {
      id: 'concrete-transport-truck-management',
      title: t('concrete-transport-truck-management.title'),
      breadcrumbs: t('concrete-transport-truck-management.breadcrumbs'),
      category: t('concrete-transport-truck-management.category'),
      website: 'www.dufago.com.vn',
      description: t('concrete-transport-truck-management.description'),
      content: locale === 'jp' ? CONCRETE_TRANSPORT_TRUCK_MANAGEMENT_JP : CONCRETE_TRANSPORT_TRUCK_MANAGEMENT,
      createdAt: '27 June 2023',
      heroUrl: '/assets/images/caseStudies/concrete-transport-truck-management-hero.png',
      galleryImgs: false,
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Trong Tran',
        role: t('concrete-transport-truck-management.role'),
        avatarUrl: '/assets/images/avatar/customer/trong-tran.jpg',
        review: t('concrete-transport-truck-management.review'),
      },
    },
    {
      id: 'huytan-customer-relationship-management',
      title: t('huytan-customer-relationship-management.title'),
      breadcrumbs: t('huytan-customer-relationship-management.breadcrumbs'),
      category: t('huytan-customer-relationship-management.category'),
      website: null,
      description: t('huytan-customer-relationship-management.description'),
      content: locale === 'jp' ? HUYTAN_CUSTOMER_RELATIONSHIP_MANAGEMENT_JP : HUYTAN_CUSTOMER_RELATIONSHIP_MANAGEMENT,
      createdAt: '05 May 2023',
      heroUrl: '/assets/images/caseStudies/huytan-customer-relationship-management-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/huytan-customer-relationship-management-img-1.png',
        '/assets/images/caseStudies/huytan-customer-relationship-management-img-2.png',
        '/assets/images/caseStudies/huytan-customer-relationship-management-img-3.png',
        '/assets/images/caseStudies/huytan-customer-relationship-management-img-4.png',
      ],
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MSSQL',
      },
      testimonial: {
        name: 'Nga Pham',
        role: t('huytan-customer-relationship-management.role'),
        avatarUrl: '/assets/images/avatar/customer/nga-pham.jpg',
        review: t('huytan-customer-relationship-management.review'),
      },
    },
    {
      id: 'ngoc-thi-honda-motorcycle-dealer',
      title: t('ngoc-thi-honda-motorcycle-dealer.title'),
      breadcrumbs:  t('ngoc-thi-honda-motorcycle-dealer.breadcrumbs'),
      category:  t('ngoc-thi-honda-motorcycle-dealer.category'),
      website: '',
      description: t('ngoc-thi-honda-motorcycle-dealer.description'),
      content: locale === 'jp' ? NGOC_THY_HONDA_MOTORCYCLE_DEALER_JP : NGOC_THY_HONDA_MOTORCYCLE_DEALER,
      createdAt: '28 October 2022',
      heroUrl: '/assets/images/caseStudies/ngoc-thi-honda-motorcycle-dealer-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/ngoc-thi-honda-motorcycle-dealer-img-1.png',
        '/assets/images/caseStudies/ngoc-thi-honda-motorcycle-dealer-img-2.png',
        '/assets/images/caseStudies/ngoc-thi-honda-motorcycle-dealer-img-3.png',
      ],
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MSSQL',
      },
      testimonial: {
        name: 'Hien Hoang',
        role: t('ngoc-thi-honda-motorcycle-dealer.role'),
        avatarUrl: '/assets/images/avatar/customer/hien-hoang.png',
        review: t('ngoc-thi-honda-motorcycle-dealer.review'),
      },
    },
    {
      id: 'thieu-yen-honda-motorcycle-dealer',
      title: t('thieu-yen-honda-motorcycle-dealer.title'),
      breadcrumbs: t('thieu-yen-honda-motorcycle-dealer.breadcrumbs'),
      category: t('thieu-yen-honda-motorcycle-dealer.category'),
      website: false,
      description: t('thieu-yen-honda-motorcycle-dealer.description'),
      content: locale === 'jp' ? THIEU_YEN_HONDA_MOTORCYCLE_DEALER_JP : THIEU_YEN_HONDA_MOTORCYCLE_DEALER,
      createdAt: '05 September 2022',
      heroUrl: '/assets/images/caseStudies/thieu-yen-honda-motorcycle-dealer-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/thieu-yen-honda-motorcycle-dealer-img-1.png',
        '/assets/images/caseStudies/thieu-yen-honda-motorcycle-dealer-img-2.png',
      ],
      technologies: {
        frontend: 'WinForms',
        backend: 'C#',
        database: 'MSSQL',
      },
      testimonial: {
        name: 'Khanh Phan',
        role: t('thieu-yen-honda-motorcycle-dealer.role'),
        avatarUrl: '/assets/images/avatar/customer/khanh-phan.jpeg',
        review: t('thieu-yen-honda-motorcycle-dealer.review'),
      },
    },
    {
      id: 'vinfast-auto-thanh-hoa',
      title: t('vinfast-auto-thanh-hoa.title'),
      breadcrumbs: t('vinfast-auto-thanh-hoa.breadcrumbs'),
      category: t('vinfast-auto-thanh-hoa.category'),
      website: 'www.vinfast-thanhhoa.com',
      description: null,
      content: locale === 'jp' ? VINFAST_AUTO_THANH_HOA_JP : VINFAST_AUTO_THANH_HOA,
      createdAt: '30 October 2023',
      heroUrl: '/assets/images/caseStudies/vinfast-auto-thanh-hoa-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/vinfast-auto-thanh-hoa-img-1.png',
        '/assets/images/caseStudies/vinfast-auto-thanh-hoa-img-2.png',
      ],
      technologies: {
        frontend: 'Bootstrap, ReactJS',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Dung Le',
        role:  t('vinfast-auto-thanh-hoa.role'),
        avatarUrl: '/assets/images/avatar/customer/dung-le.jpg',
        review: t('vinfast-auto-thanh-hoa.review'),
      },
    },
    {
      id: 'ruou-ngon',
      title: t('ruou-ngon.title'),
      breadcrumbs: t('ruou-ngon.breadcrumbs'),
      category: t('ruou-ngon.category'),
      website: 'www.ruoungon.vn',
      description: t('ruou-ngon.description'),
      content: locale === 'jp' ? RUOU_NGON_JP : RUOU_NGON,
      createdAt: '19 September 2023',
      heroUrl: '/assets/images/caseStudies/ruou-ngon-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/ruou-ngon-img-1.png',
        '/assets/images/caseStudies/ruou-ngon-img-2.png',
      ],
      technologies: {
        frontend: 'Bootstrap, ReactJS',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Ngoc Mai',
        role: t('ruou-ngon.role'),
        avatarUrl: '/assets/images/avatar/customer/ngoc-mai.jpg',
        review: t('ruou-ngon.review'),
      },
    },
    {
      id: 'power-bi',
      title: t('power-bi.title'),
      breadcrumbs: t('power-bi.breadcrumbs'),
      category: t('power-bi.category'),
      website: 'www.quoctien.vn',
      description: t('power-bi.description'),
      content: locale === 'jp' ? POWER_BI_JP : POWER_BI,
      createdAt: '25 October 2019',
      heroUrl: '/assets/images/caseStudies/power-bi-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/power-bi-img-1.png',
        '/assets/images/caseStudies/power-bi-img-2.png',
      ],
      technologies: {
        frontend: 'Power BI Desktop, Power BI Mobile',
        backend: 'Power BI Service',
        database: 'MSSQL',
      },
      testimonial: {
        name: 'Hien Dinh',
        role: t('power-bi.role'),
        avatarUrl: '/assets/images/avatar/customer/hien-dinh.jpg',
        review: t('power-bi.review'),
      },
    },
    {
      id: 'quoc-tien-honda-motorcycle-dealer',
      title: t('quoc-tien-honda-motorcycle-dealer.title'),
      breadcrumbs: t('quoc-tien-honda-motorcycle-dealer.breadcrumbs'),
      category: t('quoc-tien-honda-motorcycle-dealer.category'),
      website: 'www.quoctien.vn',
      description: t('quoc-tien-honda-motorcycle-dealer.description'),
      content: locale === 'jp' ? QUOCTIEN_CUSTOMER_RELATIONSHIP_MANAGEMENT_JP : QUOCTIEN_CUSTOMER_RELATIONSHIP_MANAGEMENT,
      createdAt: '30 March 2018',
      heroUrl: '/assets/images/caseStudies/quoc-tien-honda-motorcycle-dealer-hero.png',
      galleryImgs: [
        '/assets/images/caseStudies/quoc-tien-honda-motorcycle-dealer-img-1.png',
        '/assets/images/caseStudies/quoc-tien-honda-motorcycle-dealer-img-2.png',
      ],
      technologies: {
        frontend: 'UiPath Studio',
        backend: 'UiPath Service',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Vu Nguyen',
        role: t('quoc-tien-honda-motorcycle-dealer.role'),
        avatarUrl: '/assets/images/avatar/customer/vu-nguyen.jpg',
        review: t('quoc-tien-honda-motorcycle-dealer.review'),
      },
    },
    {
      id: 'quoc-tien-app-dros',
      title: t('quoc-tien-app-dros.title'),
      breadcrumbs: t('quoc-tien-app-dros.breadcrumbs'),
      category: t('quoc-tien-app-dros.category'),
      website: 'www.quoctien.vn',
      description:  t('quoc-tien-app-dros.description'),
      content: locale === 'jp' ? QUOCTIEN_APP_DROS_JP : QUOCTIEN_APP_DROS,
      createdAt: '19 September 2023',
      heroUrl: '/assets/images/caseStudies/quoc-tien-app-dros-hero.png',
      galleryImgs: false,
      technologies: {
        frontend: 'Bootstrap, Jquery',
        backend: 'PHP Laravel',
        database: 'MySQL',
      },
      testimonial: {
        name: 'Hieu Nguyen',
        role: t('quoc-tien-app-dros.role'),
        avatarUrl: '/assets/images/avatar/customer/hieu-nguyen.jpg',
        review:t('quoc-tien-app-dros.review'),
      },
    },
  ]

export const getCurentCaseStudies = (t, locale = 'en') => {

  const datas = getDatas(t, locale);

  return datas.map((data, index) => ({
    ...data,
    coverUrl: `/assets/images/marketing/marketing_${index + 1}.jpg`,
    imageSrc: `/assets/images/marketing/marketing_${index + 1}.jpg`,
    technologies: {
      ...data.technologies,
    },
    testimonial: {
      ...data.testimonial,
    },
  }))
}
